<#--<!DOCTYPE html>-->
<#--<html lang="en">-->
<#--<head>-->
<#--    <meta charset="UTF-8">-->
<#--    <title>Books</title>-->
<#--&lt;#&ndash;    <link rel="stylesheet" href="book.css"  type="text/css">&ndash;&gt;-->
<#--    <link rel="stylesheet" href="style.css"  type="text/css">-->
<#--</head>-->
<#--<body>-->
<footer>
    <p>Barkhatova Irina</p>
    <p>2023</p>
</footer>
<#--</body>-->
<#--</html>-->