<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Books</title>
    <link rel="stylesheet" href="css/style.css" type="text/css">
</head>
<body>
<#include 'fragments/header.ftlh'>
<div class="container">
<#--<h2>Login form ${logout}</h2>-->
<a href="/login">Login</a>
<#--        <form action="/index" method="get">-->
<#--            <label for="username">Username:</label>-->
<#--            <input type="text" id="username" name="username" placeholder="username">-->
<#--            <label for="password">Password:</label>-->
<#--            <input type="password"  id="password" placeholder="password">-->
<#--            <button type="submit">Login</button>-->
<#--        </form>-->
</div>
<#include 'fragments/footer.ftlh'>
</body>
</html>